### ISSUE TITLE
[SE Issue] 

### ISSUE THREAD

**Issue by Jmp86** [learn-co-curriculum/phase-3-active-record-associations-tvland-lab#4]
### Canvas Link

https://learning.flatironschool.com/courses/2661/assignments/99151?module_item_id=202489

### Concern

This lab won't run the tests correctly. It is pre loaded with code that pass a few of the test and as soon as I add any of my own code all of the test fail including the preloaded passing tests. Tried to find any missing gems and any problems  with the config file. Nothing worked

**Comment by lizbur10** [comment]
Hi @Jmp86 ! Sorry to hear you're running into problems with this lab! 

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you haven't already, I recommend that you contact your cohort lead, section lead or [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) to get assistance with this issue. 

Otherwise, if you can provide further detail about the steps required to reproduce the issue and specific errors you're getting, I'd be happy to take a second look!

Thanks for contributing to the Flatiron School curriculum! 💙
